<?php $this->headTitle()->prepend($this->translate('My Facebook Profile')); ?>

<?php 
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', '/facebook/save');
    $form->setAttribute('method', 'post');
    echo $this->form()->openTag($form);
?>
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <h2><i class="fa fa-facebook"></i> Facebook Sync <small><?php echo $this->translate('Set your default public facebook page')?></small></h2>
                <hr/>
                <p><?php echo $this->translate('Here you control the events will be shared in this website. When you set your facebook page here, the events on that page are public as well meaning that people can search for it and find it in a variety of ways, including via Google Web search.')?></p>
                <p>
                    <a class="btn btn-primary" href="<?php echo $this->facebooklogin() ?>"><i class="fa fa-facebook"></i> <?php echo $this->translate('ReAuthorize Facebook')?></a>
                    <a class="btn btn-danger" href="https://www.facebook.com/settings?tab=applications" target="_blank"><i class="fa fa-times"></i> <?php echo $this->translate('Revoke the access to the facebook event')?></a>
                </p>
                <br/>
                
                <?php echo $this->formLabel($form->get('pages')); ?>
                <div class="input-group">
                  <?php echo $this->formElement($form->get('pages')); ?>
                  <div class="input-group-btn">
                    <a href="/facebook/pages" tabindex="-1" class="btn btn-primary" type="button"><i class="fa fa-refresh"></i> <?php echo $this->translate('Refresh pages')?></a>
                  </div>
                </div>
                <?php echo $this->formElementErrors($form->get('pages')); ?>
            </div>
            <div class="panel panel-default">
              <div class="panel-body">
                <?php echo $this->translate('Warning! All the previous events synced in this website will be deleted and synced again!')?>
              </div>
            </div>
            <div class="text-right">
        	    <?php echo $this->formElement($form->get('submit')); ?>
        	</div>
        </div>
    </div>
</div>

<?php echo $this->form()->closeTag() ?>